name: PR checks

on:
  pull_request:
    branches:
      - checker

jobs:
  dco:
    name: DCO compliance
    runs-on: ubuntu-latest #让工作流运行在 ubuntu的最新版本上
    steps: # 要执行的动作
      - name: Run dco-check
        uses: christophebedard/dco-check@0.5.0 # 一个现成的action DCO 合规校验工具
        with:
          python-version: '3.12'
          args: '--verbose'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
